### ISSUE TITLE
About xcontrol 

### ISSUE THREAD

**Issue by Ayho** [JellyBitz/phBot-xPlugins#1]
hi. first of all ı am making auto temple. the problem is when ı killed the osiris ı am using the GETOUT command but my characters writing GETOUTwalk command and they do not leave the temple. they are using return scroll and they they are going to town. how can ı solve this problem ?

**Comment by JellyBitz** [comment]
GETOUT it's to demand to the player to leave the current party if they has one.
**It's not a script command.**

If you want to use it on script, you should use `inject,7061,False` on the end before using return scroll.
