### ISSUE TITLE
xAcademy: Deletion minutes left data unpacked incorrectly [TRSRO]

### ISSUE THREAD

**Issue by buracc** [JellyBitz/phBot-xPlugins#3]
The minutesLeft variable is an incorrect number, I think the wrong bytes are unpacked. The 4 bytes that come after the character deletion flag need to be skipped, and the next two bytes are the remaining amount of minutes. I fixed it like so:
```python
character['is_deleting'] = data[index]
index+=1 # isDeleting
if character['is_deleting']:
	index+=4 # minutes left
	minutesLeft = struct.unpack_from('<H',data,index)[0]
	character['deleted_at'] = datetime.now() + timedelta(minutes=minutesLeft)
```

After doing this it returns the correct amount of minutes. However, I have only tested this in TRSRO so I'm not sure if it also applies to iSRO. I'm not an expert so I could be terribly wrong. Hope I could help.

**Comment by JellyBitz** [comment]
It works correctly on vSRO.

Yes, the structure changed more than I expected on iSRO files.
