### ISSUE TITLE
About JellyDix Consignment notices

### ISSUE THREAD

**Issue by genetech16** [JellyBitz/phBot-xPlugins#4]
Hi,
Right now its working perfect, there's no issues about notifications, but I'd like to sen different messages.
Right now bot send messages just like trade will start, trade started and trade ended.

But in game notifications shows trade will start soon in jangan, and hotan whichever town it is.
Can we send whole consignment notification to discord ? like we see it in game ?

if we can how can i change it ? can you help me about this ?

Note : i dont have a development knowledge almost at all :)

**Comment by JellyBitz** [comment]
Try to use xPacketTool and tick "Show server packets" right before it happens.
I'll take a look into the data to extract the town name.
